web/app/urls.py
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from . import views
from .profile.views import ProfileView, image_upload_ajax, user_site

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('account/profile/<user>/image/', image_upload_ajax, name='image_upload'),
    path('account/profile/<user>/user_site/', user_site, name='user_site'),
    path('account/profile/<user>', ProfileView.as_view(), name='user-profile'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
]

web/posts/urls.py
from django.urls import path, include
from django.contrib.auth.decorators import login_required
from .views import ArticleListView, ArticleDetailView, \
    LeaveComment, ArticleCreateView, ArticleDeleteView, SectionView
from likes.models import LikeDislike
from likes.views import VotesView
from .models import ArticleModel, Comment

app_name = 'articles'

urlpatterns = [
    path('', ArticleListView.as_view(), name='article-list'),
    path('create/', ArticleCreateView.as_view(), name='article-create'),
    path('api/', include('posts.api.urls')),
    path('<section>/', SectionView.as_view(), name='section'),
    path('<section>/<slug>/', ArticleDetailView.as_view(), name='article-detail'),
    path('<section>/<slug>/leave_comment/', LeaveComment.as_view(), name='leave_comment'),
    path('<section>/<slug>/delete/', ArticleDeleteView.as_view(), name='article-delete'),
]

# likes
urlpatterns += [
    path('<section>/<slug>/like/',
         login_required(VotesView.as_view(model=ArticleModel, vote_type=LikeDislike.LIKE)),
         name='article_like'),
    path('<section>/<slug>/dislike/',
         login_required(VotesView.as_view(model=ArticleModel, vote_type=LikeDislike.DISLIKE)),
         name='article_dislike'),
    path('<section>/<slug>/comment/like/',
         login_required(VotesView.as_view(model=Comment, vote_type=LikeDislike.LIKE)),
         name='comment_like'),
    path('<section>/<slug>/comment/dislike/',
         login_required(VotesView.as_view(model=Comment, vote_type=LikeDislike.DISLIKE)),
         name='comment_dislike'),
]

web/src/urls.py
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include
from django.conf.urls.static import static
from app.sitemaps import ArticleSitemap, StaticViewSitemap, ProfileSitemap
from app.views import custom_handler404, custom_handler500


sitemaps: dict = {
    'articles': ArticleSitemap,
    'profile': ProfileSitemap,
    'static': StaticViewSitemap,
}

urlpatterns = [
    path('', include('app.urls')),
    path('p/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}),
    # path('admin/defender/', include('defender.urls')),
    path('accounts/', include('allauth.urls')),
    path('api-auth/', include('rest_framework.urls')),

]

# handler404 = 'app.views.custom_handler404'
# handler500 = 'app.views.custom_handler500'

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block head_title %}{% endblock %}</title>
    {% block extra_head %}
    {% endblock %}
  </head>
  <body>
    {% block body %}

    {% if messages %}
    <div>
      <strong>Messages:</strong>
      <ul>
        {% for message in messages %}
        <li>{{message}}</li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}

    <div>
      <strong>Menu:</strong>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'account_email' %}">Change E-mail</a></li>
        <li><a href="{% url 'account_logout' %}">Sign Out</a></li>
        {% else %}
        <li><a href="{% url 'account_login' %}">Sign In</a></li>
        <li><a href="{% url 'account_signup' %}">Sign Up</a></li>
        {% endif %}
      </ul>
    </div>
    {% block content %}
    {% endblock %}
    {% endblock %}
    {% block extra_body %}
    {% endblock %}
  </body>
</html>

web/templates/layer.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %}Social Network{% endblock %} </title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'app/styles/bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/styles/site.css' %}" />
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
    <script src="{% static 'app/scripts/jquery-3.4.1.min.js' %}"></script>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <script src="https://kit.fontawesome.com/fe539a9d82.js" crossorigin="anonymous"></script>
    {% block head %} {% endblock %}
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">Social Network</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'main:index' %}"><i class="fa fa-home"></i> Home</a></li>
                    <li><a href="{% url 'articles:article-list' %}"><i class="fas fa-newspaper"></i> Articles</a></li>
                </ul>
                {% include 'loginpartial.html' %}

                <ul class="nav navbar-nav ">

                </ul>

            </div>
        </div>
    </div>
    <div class="container body-content">
    {% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>&copy; {% now "Y" %} - Social Network</p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    {% block scripts %}{% endblock %}
    <script>
        $(document).ready(function(){
            {% block jquery %} {% endblock %}
        })
    </script>

</body>
</html>

web/templates/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout/" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">
            {% if user.is_staff %}
            <a target="_blank" style="text-decoration: none" href="/admin/"> Hello {{ user.username }}!</a>

            {% else %}
                Hello {{ user.username }}!
            {% endif %}
            <a href="{% url 'main:user-profile' user %}"><i class="fas fa-user-circle"></i> Profile</a>
        </span></li>
        <li><span class="navbar-brand">
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'account_login' %}">Sign in</a></li>
    <li><a href="{% url 'account_signup' %}">Sign up</a></li>
</ul>

{% endif %}